PACKAGE = mythtv_services_api

SOURCES = \
	setup.py \
	setup.cfg \
	unittests.py \
	$(PACKAGE)/send.py \
	$(PACKAGE)/utilities.py \
	$(PACKAGE)/__init__.py \
	$(PACKAGE)/_version.py

usage:
	@echo "\nUse: make target VERSION=M.m.f, e.g. make install VERSION=0.1.9\n"

install: unittests uninstall
	@echo "Installing VERSION: $(VERSION)"
	@python2 setup.py bdist_wheel
	@sudo -H pip2 install dist/$(PACKAGE)-$(VERSION)-py2-none-any.whl
	@python3 setup.py bdist_wheel
	@sudo -H pip3 install dist/$(PACKAGE)-$(VERSION)-py3-none-any.whl

push: version unittests
	@echo "Pushing VERSION: $(VERSION)"
	@git add dist/$(PACKAGE)-$(VERSION)-py?-none-any.whl
	@git commit --message "Latest .whls for: $(VERSION)." \
		dist/$(PACKAGE)-$(VERSION)-py?-none-any.whl
	@git tag --annotate $(VERSION) --message "Tag generated by: make push"
	@git push

clean:
	@rm -f  $(PACKAGE)/*.pyc
	@rm -rf $(PACKAGE)/__pycache__
	@rm -rf $(PACKAGE).egg-info
	@rm -rf build/*

clobber:version  clean
	@echo "Clobbering VERSION: $(VERSION)"
	@git rm -f --ignore-unmatch dist/$(PACKAGE)-$(VERSION)-py?-none-any.whl

unittests:
	./unittests.py

uninstall: clobber
	sudo -H pip2 uninstall $(PACKAGE) || :
	sudo -H pip3 uninstall $(PACKAGE) || :

version:
	@test -n "$(VERSION)" || (echo "\nVERSION wasn't set!\n" && exit 1)

# vim: set colorcolumn=80 noexpandtab:
