PACKAGE = mythtv_services_api

SOURCE = \
	setup.py \
	setup.cfg \
	unittests.py \
	$(PACKAGE)/send.py \
	$(PACKAGE)/utilities.py \
	$(PACKAGE)/__init__.py \
	$(PACKAGE)/_version.py

usage:
	@echo "\nUse: make install/uninstall/clean/clobber/push [VERSION=1.2.3]\n"

install: uninstall
	@echo "Installing VERSION: $(VERSION)"
	@python2 setup.py bdist_wheel
	@sudo -H pip2 install dist/$(PACKAGE)-$(VERSION)-py2-none-any.whl
	@python3 setup.py bdist_wheel
	@sudo -H pip3 install dist/$(PACKAGE)-$(VERSION)-py3-none-any.whl

push:
	@test -n "$(VERSION)" || (echo "\nVERSION wasn't set!\n" && exit 1)
	@echo "Pushing VERSION: $(VERSION)"
	@git add dist/$(PACKAGE)-$(VERSION)-py?-none-any.whl
	@git commit --message "Latest .whls for: $(VERSION)." \
		dist/$(PACKAGE)-$(VERSION)-py?-none-any.whl
	@git tag --annotate $(VERSION) --message "Tag generated by: make push"
	@git push

clean:
	@rm -f  $(PACKAGE)/*.pyc
	@rm -rf $(PACKAGE)/__pycache__
	@rm -rf $(PACKAGE).egg-info
	@rm -rf build/*

clobber: clean
	@test -n "$(VERSION)" || (echo "\nVERSION wasn't set!\n" && exit 1)
	@echo "Clobbering VERSION: $(VERSION)"
	@git rm -f --ignore-unmatch dist/$(PACKAGE)-$(VERSION)-py?-none-any.whl

uninstall: clobber
	sudo -H pip2 uninstall $(PACKAGE) || :
	sudo -H pip3 uninstall $(PACKAGE) || :
